# Using Union

(Select Employee_Id, Department_Id
From Employee
Where Primary_Flag = 'Y'
)
Union
(Select Employee_Id, Department_Id
From Employee
Group By Employee_Id
Having Count(Department_Id) = 1);


# Normal 

SELECT EMPLOYEE_ID, DEPARTMENT_ID
FROM EMPLOYEE
WHERE EMPLOYEE_ID IN 
(
    SELECT EMPLOYEE_ID  
    FROM EMPLOYEE
    GROUP BY EMPLOYEE_ID
    HAVING COUNT(DEPARTMENT_ID) = 1
)
OR PRIMARY_FLAG = 'Y';


# Using another table

WITH TEMP AS(
    SELECT EMPLOYEE_ID, COUNT(DEPARTMENT_ID) AS COUNTER
    FROM EMPLOYEE
    GROUP BY EMPLOYEE_ID
)
SELECT EMPLOYEE_ID, DEPARTMENT_ID FROM (SELECT E.EMPLOYEE_ID,
CASE
    WHEN T.COUNTER = 1 OR E.PRIMARY_FLAG = 'Y' THEN E.DEPARTMENT_ID
    ELSE 0
END AS DEPARTMENT_ID
FROM EMPLOYEE E INNER JOIN TEMP T
ON E.EMPLOYEE_ID = T.EMPLOYEE_ID) AS NEW
WHERE DEPARTMENT_ID <> 0;
